DROP TABLE IF EXISTS `adventure_gear`;
CREATE TABLE `adventure_gear` (item VARCHAR(100), price DECIMAL(6,2), weight DECIMAL(4, 2));

INSERT INTO adventure_gear VALUES ("Acid (flask)", 25, 1);
INSERT INTO adventure_gear VALUES ("Adventurer's kit", 9, 39);
INSERT INTO adventure_gear VALUES ("Alchemist's fire (flask)", 50, 1);
INSERT INTO adventure_gear VALUES ("Antitoxin (vial)", 50, NULL);
INSERT INTO adventure_gear VALUES ("Arrows (20)", 1, 3);
INSERT INTO adventure_gear VALUES ("Artisan's tools", 5, 5);
INSERT INTO adventure_gear VALUES ("Backpack (empty)", 2, 2);
INSERT INTO adventure_gear VALUES ("Ball bearings (100)", 1, 1);
INSERT INTO adventure_gear VALUES ("Bedroll", 1, 5);
INSERT INTO adventure_gear VALUES ("Bell", 1, NULL);
INSERT INTO adventure_gear VALUES ("Blankey, winter", 0.5, 3);
INSERT INTO adventure_gear VALUES ("Block and Tackle", 1, 5);
INSERT INTO adventure_gear VALUES ("Bolts, crossbow (10)", 1, 3);
INSERT INTO adventure_gear VALUES ("Bucket (empty)", .05, 2);
INSERT INTO adventure_gear VALUES ("Bullet, sling (10)", .02, 1);
INSERT INTO adventure_gear VALUES ("Caltrops", 1, 2);
INSERT INTO adventure_gear VALUES ("Candle, tallow", .01, .1);
INSERT INTO adventure_gear VALUES ("Case, map or scroll", 1, 1);
INSERT INTO adventure_gear VALUES ("Chain (10 feet)", 5, 5);
INSERT INTO adventure_gear VALUES ("Chalk (1 piece)", .01, NULL);
INSERT INTO adventure_gear VALUES ("Climber's kit", .03, 5);
INSERT INTO adventure_gear VALUES ("Clothes, common", .5, 3);
INSERT INTO adventure_gear VALUES ("Clothes, costume", 5, 4);
INSERT INTO adventure_gear VALUES ("Clothes, fine", 15, 6);
INSERT INTO adventure_gear VALUES ("Clothes, traveler's", 2, 4);
INSERT INTO adventure_gear VALUES ("Crowbar", .2, 5);
INSERT INTO adventure_gear VALUES ("Disguise kit", 25, 8);
INSERT INTO adventure_gear VALUES ("Fishing tackle", 1, 8);
INSERT INTO adventure_gear VALUES ("Flask (clay)", .02, NULL);
INSERT INTO adventure_gear VALUES ("Grappling hook", 2, 4);
INSERT INTO adventure_gear VALUES ("Hammer, basic", .2, 2);
INSERT INTO adventure_gear VALUES ("Healer's kit", 5, 1);
INSERT INTO adventure_gear VALUES ("Healing poition", 50, 1);
INSERT INTO adventure_gear VALUES ("Holy Symbol", 5, NULL);
INSERT INTO adventure_gear VALUES ("Holy Water (flask)", 25, 1);
INSERT INTO adventure_gear VALUES ("Hourglass", 5, 1);
INSERT INTO adventure_gear VALUES ("Hunting trap", 5, 15);
INSERT INTO adventure_gear VALUES ("Ink (1-ounce vial", 10, NULL);
INSERT INTO adventure_gear VALUES ("Ink pen", .02, NULL);
INSERT INTO adventure_gear VALUES ("Jug (clay)", .02, 9);
INSERT INTO adventure_gear VALUES ("Ladder (10-foot)", .1, 20);
INSERT INTO adventure_gear VALUES ("Lamp, common", .5, 1);
INSERT INTO adventure_gear VALUES ("Lantern, bullseye", 10, 3);
INSERT INTO adventure_gear VALUES ("Lantern, hooded", 5, 2);
INSERT INTO adventure_gear VALUES ("Lock", 10, 1);
INSERT INTO adventure_gear VALUES ("Magnifying glass", 100, .1);
INSERT INTO adventure_gear VALUES ("Manacles", 2, 2);
INSERT INTO adventure_gear VALUES ("Mess kit", .1, 1);
INSERT INTO adventure_gear VALUES ("Mirror, small, steel", 5, .5);
INSERT INTO adventure_gear VALUES ("Musical instrument", 5, 3);
INSERT INTO adventure_gear VALUES ("Oil (1-pint flask)", .1, 1);
INSERT INTO adventure_gear VALUES ("Paper (sheet)", .2, NULL);
INSERT INTO adventure_gear VALUES ("Parchment (sheet)", .1, NULL);
INSERT INTO adventure_gear VALUES ("Pick, miner's", .5, 10);
INSERT INTO adventure_gear VALUES ("Piton", .05, .5);
INSERT INTO adventure_gear VALUES ("Poison, basic (vial)", 100, NULL);
INSERT INTO adventure_gear VALUES ("Pole (10-foot)", .05, 8);
INSERT INTO adventure_gear VALUES ("Pot, iron", .1, 10);
INSERT INTO adventure_gear VALUES ("Pouch, belt (empty)", 1, 10);
INSERT INTO adventure_gear VALUES ("Ram, portable", 1, 20);
INSERT INTO adventure_gear VALUES ("Rations (1 day)", .1, 1);
INSERT INTO adventure_gear VALUES ("Ritual component pouch", NULL, 2);
INSERT INTO adventure_gear VALUES ("Robes", 1, 4);
INSERT INTO adventure_gear VALUES ("Rope, hempen (50 feet)", 1, 10);
INSERT INTO adventure_gear VALUES ("Rope, silk (50 feet)", 10, 5);
INSERT INTO adventure_gear VALUES ("Sack", .01, .5);
INSERT INTO adventure_gear VALUES ("Scale, merchant's", 5, 1);
INSERT INTO adventure_gear VALUES ("Sealing wax", .5, 1);
INSERT INTO adventure_gear VALUES ("Signal whistle", .05, NULL);
INSERT INTO adventure_gear VALUES ("Signet ring", 5, NULL);
INSERT INTO adventure_gear VALUES ("Sledge", .5, 10);
INSERT INTO adventure_gear VALUES ("Soap", .02, 1);
INSERT INTO adventure_gear VALUES ("Spade or shovel", .5, 8);
INSERT INTO adventure_gear VALUES ("Spellbook (blank)", 75, 3);
INSERT INTO adventure_gear VALUES ("Spike, iron (10)", .02, 5);
INSERT INTO adventure_gear VALUES ("Spyglass", 1000, 1);
INSERT INTO adventure_gear VALUES ("Tent", 2, 20);
INSERT INTO adventure_gear VALUES ("Thieves' tool", 25, 1);
INSERT INTO adventure_gear VALUES ("Tinderbox", .5, 1);
INSERT INTO adventure_gear VALUES ("Tome", 25, 5);
INSERT INTO adventure_gear VALUES ("Torch", .01, 1);
INSERT INTO adventure_gear VALUES ("Vial", 1, .1);
INSERT INTO adventure_gear VALUES ("Waterskin (full)", .2, 4);
INSERT INTO adventure_gear VALUES ("Whetstone", .01, 1);

