DROP TABLE IF EXISTS `trinkets`;
CREATE TABLE trinkets (id INTEGER AUTO_INCREMENT, trinket VARCHAR(120), PRIMARY KEY (id));

INSERT INTO trinkets (trinket) VALUES ("A mummified goblin hand"),
  ("A piece of crystal that faintly glows in the moonlight"),
  ("A gold coin minted in an unkown land"),
  ("A diary written in a language you don't know"),
  ("A brass ring that never tarnishes"),
  ("An old chess piece made from glass"),
  ("A pair of knucklebone dice, each with a skull symbol on the side that would normally show size pips"),
  ("A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it"),
  ("A rope necklace from which dangles four mummified elf fingers"),
  ("The deed for a parcel of land in a realm unknown to you"),
  ("A 1-ounce block made from an unknown material"),
  ("A small cloth doll skewered with needles"),
  ("A tooth from an unknown beast"),
  ("An enormous scale, perhaps from a dragon"),
  ("A bright green feather"),
  ("An old divination card bearing your likeness"),
  ("A glass orb filled with moving smoke"),
  ("A 1-pound egg with a bright red shell"),
  ("A pipe that blows bubbles"),
  ("A glass jar containing a weird bit of flesh floating in pickling fluid"),
  ("A tiny gnome-crafted music box that plays a song you dimly remember from your childhood"),
  ("A small wooden statuette of a smug halfing"),
  ("A brass orb etched with strange runes"),
  ("A multicolored stone disk"),
  ("A tiny silver icon of a raven"),
  ("A bag containing forty-seven humanoid teeth, one of which is rotten"), 
  ("A shard of obsidian that always feels warm to the touch"),
  ("A dragon's bony talon hanging from a plain leather, necklace"),
  ("A pair of old socks"),
  ("A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance or marking"), #30
